# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-


def build(bld):
    obj = bld.create_ns3_program('visualizer3d-mobility-buildings-example',
                                 ['visualizer3d', 'core', 'mobility', 'network'])
    obj.source = 'mobility-buildings-example.cc'

    obj = bld.create_ns3_program('lena-radio-link-failure-netsimulyzer',
                                 ['visualizer3d', 'core', 'mobility', 'network', 'lte'])
    obj.source = 'lena-radio-link-failure-netsimulyzer.cc'

    obj = bld.create_ns3_program('outdoor-random-walk-example-netsimulyzer',
                                 ['visualizer3d', 'core', 'mobility', 'network', 'buildings'])
    obj.source = 'outdoor-random-walk-example-netsimulyzer.cc'

    obj = bld.create_ns3_program('wifi-bianchi-netsimulyzer',
                                 ['visualizer3d', 'core', 'mobility', 'network', 'wifi'])
    obj.source = 'wifi-bianchi-netsimulyzer.cc'
