# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-


def build(bld):
    obj = bld.create_ns3_program('visualizer3d-mobility-buildings-example',
                                 ['visualizer3d', 'core', 'mobility', 'network'])
    obj.source = 'mobility-buildings-example.cc'
